version: 0.2
env:
  secrets-manager:
    DOCKER_PW: "$DOCKER_PW"
    DOCKER_ID: "$DOCKER_ID"
phases:
  build:
    commands:
      # Log in to the Docker CLI
      - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
      - echo Build started on `date`
      # Build the Docker images
      - echo Building the production Docker image...
      - docker build -t tonycook/property-app-client ./client
      - docker build -t tonycook/property-app-api ./server
      - docker build -t tonycook/property-app-nginx ./nginx

  post_build:
    commands:
      # Take these images and push them to Docker hub
      - echo Pushing the Docker images...
      - docker push tonycook/property-app-client
      - docker push tonycook/property-app-api
      - docker push tonycook/property-app-nginx
artifacts:
  files:
    - "Dockerrun.aws.json"
